### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by EmmanuelBeziat** [EmmanuelBeziat/bns-profile#1]
## Core
* [x] Routing
* [x] Main app
* [x] Smooth anchors
* [x] Image conversion
* [ ] Make translation possible
  * [ ] Json for app texts and labels
  * [ ] Markdown file for help page

## Content
* [x] Main page app
* [x] Help page
  * [x] Content images

## Host
* [x] Hosted on surge
